base: https://blades.ninja
favicon: /favicon.svg
favicon_alt: /favicon.png
title: 11ty Blades
subtitle: Framework-agnostic, class-light CSS⁺ blade kit. Use with Pico, Simple, Tailwind, or any other CSS reset/framework.
author:
  name: Anton Staroverov
brand: <big><big><a href="/" class="dark-auto"><i>🥷</i> <span class="opt"><em>Bl</em>ades</span></a></big></big>
header_links:
  - title: '<span class="faded">|</span>'
  - url: https://github.com/anyblades
    title: <i class="fa-brands fa-github"></i>
  - url: https://x.com/any_blades
    title: <i class="fa-brands fa-x-twitter"></i>
footer_content: |
  &nbsp;&nbsp;

  [<span>*Bl*adesverse</span> <i class="faded">:</i> <i><span>![](https://img.shields.io/github/stars/anyblades?logo=_&label=🥷)</span></i>](https://github.com/anyblades?sort=stargazers)
