base: https://11ty.blades.ninja
title: Build Awesome / Eleventy Blades
brand: 11ty&nbsp;🥷&nbsp;<em>Bl</em>ades
header_links:
  - url: https://github.com/anyblades/eleventy-blades
    title: <i class="fa-brands fa-github fa-lg"></i>
  - url: https://mastodon.social/@anydigital/tagged/11tyBuildAwesome?boosts=1
    title: <i class="fa-brands fa-mastodon fa-lg"></i>
  - url: https://blades.ninja/
    title: <i class="fa-brands fa-css3 fa-sm faded"></i>
  - url: https://github.com/anyblades/awesome-11ty-buildawesome
    title: <i class="fa-solid fa-laptop-code fa-sm faded"></i>
footer_contents:
  - Code licensed [MIT](//github.com/anyblades/eleventy-blades/blob/main/LICENSE.md),
    docs [CC BY-SA 4.0](//github.com/anyblades/awesome-11ty-buildawesome/blob/master/LICENSE.md). &nbsp;
    Currently <img src="https://img.shields.io/npm/v/@anyblades/eleventy-blades?label=plugin&color=white"> <img src="https://img.shields.io/npm/v/@anyblades/eleventy-blades-base?label=base&color=white">
